{
 "title": "Costgraph Dashboard",
 "description": "Rightsizing done properly.",
 "tags": [ "costgraph" ],
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "filters" }
  ]
 },
 "panels": [
  {
   "title": "Costgraph ",
   "type": "text",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "options": {
    "content": "# Costgraph\n\nCostgraph is the foundational \"Data Driven FinOps for Modern Infrastructure\" solution to enterprise teams.\n\nCheck out the product at [costgraph.baselinehq.cloud](https://costgraph.baselinehq.cloud) and the docs at [docs.baselinehq.cloud](https://docs.baselinehq.cloud).\n\n## What does this dashboard offer?\n\nThis dashboard offers an aggregate look at the metrics costgraph provides, this crosses metrics for\n- costs \n- rightsizings\n- usage \n- resource breakdown"
   }
  },
  {
   "title": "FAQs ",
   "type": "text",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "options": {
    "content": "## Is this the best dashboard?\n\nAs much as Prometheus and Grafana are a standard, there are limits to its dashboard capabilities with its columnar driven data pattern.\n\nIt is recommended to use the Superset dashboard if you desire finer metrics and better visuals, this will work just fine for most of your needs.\n\n\n## Does this get updated?\n\nIt might after a while. Check out the [costgraph-manifests repository](https://github.com/baselinehq/costgraph-manifests) for new updates to the dashboard json."
   }
  },
  {
   "title": "(intentionally empty)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 },
   "collapsed": true
  },
  {
   "title": "Leadership",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 },
   "collapsed": true,
   "panels": [
    {
     "title": "Current Spend",
     "type": "stat",
     "description": "Aggregate current spend for the organization.",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 10 },
     "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(costgraph_namespace_recommendation_current_spend)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Savings",
     "type": "stat",
     "description": "Aggregate savings for the organization.",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 10 },
     "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(costgraph_namespace_recommendation_total_resource_savings_amount)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "New Spend",
     "type": "stat",
     "description": "Aggregate new spend for the organization.",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 10 },
     "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(costgraph_namespace_recommendation_new_spend)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Total CPU Requests",
     "type": "stat",
     "description": "CPU requests used across the organization.",
     "gridPos": { "h": 7, "w": 6, "x": 0, "y": 170 },
     "fieldConfig": { "defaults": { "unit": "cores" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(costgraph_namespace_recommendation_total_cpu_requests)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Total CPU Limits",
     "type": "stat",
     "description": "CPU llimits used across the organization.",
     "gridPos": { "h": 7, "w": 6, "x": 6, "y": 170 },
     "fieldConfig": { "defaults": { "unit": "cores" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(costgraph_namespace_recommendation_total_cpu_limits)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Total Memory Requests",
     "type": "stat",
     "description": "Memory requests used across the organization.",
     "gridPos": { "h": 7, "w": 6, "x": 12, "y": 170 },
     "fieldConfig": { "defaults": { "unit": "decgbytes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(costgraph_namespace_recommendation_total_memory_requests)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Total Memory Limits",
     "type": "stat",
     "description": "Memory limits used across the organization.",
     "gridPos": { "h": 7, "w": 6, "x": 18, "y": 170 },
     "fieldConfig": { "defaults": { "unit": "decgbytes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(costgraph_namespace_recommendation_total_memory_limits)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Aggregate Node Pricing",
     "type": "stat",
     "description": "Details the monthly cost of all nodes in your organisation",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 177 },
     "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "(sum(costgraph_cluster_capacity_nodes_pricing_vcpu_cost)  + sum(costgraph_cluster_capacity_nodes_pricing_ram_cost)) * 24 * 30",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "CPU Request Rightsizings",
     "type": "table",
     "description": "Before and After observations of rightsizing values across clusters.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 184 },
     "fieldConfig": { "defaults": { "unit": "cores" } },
     "targets": [
      {
       "expr": "sum(costgraph_namespace_recommendation_total_cpu_requests) by (cluster)"
      },
      {
       "expr": "sum(costgraph_namespace_recommendation_total_cpu_requests - costgraph_namespace_recommendation_total_cpu_requests_savings) by (cluster)"
      }
     ]
    },
    {
     "title": "CPU Limit Rightsizings",
     "type": "table",
     "description": "Before and After observations of rightsizing values across clusters.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 184 },
     "fieldConfig": { "defaults": { "unit": "cores" } },
     "targets": [
      {
       "expr": "sum(costgraph_namespace_recommendation_total_cpu_limits) by (cluster)"
      },
      {
       "expr": "sum(costgraph_namespace_recommendation_total_cpu_limits - costgraph_namespace_recommendation_total_cpu_limits_savings) by (cluster)"
      }
     ]
    },
    {
     "title": "Memory Request Rightsizings",
     "type": "table",
     "description": "Before and After observations of rightsizing values across clusters.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 192 },
     "fieldConfig": { "defaults": { "unit": "decgbytes" } },
     "targets": [
      {
       "expr": "sum(costgraph_namespace_recommendation_total_memory_requests) by (cluster)",
       "legendFormat": "__auto"
      },
      {
       "expr": "sum(costgraph_namespace_recommendation_total_memory_requests - costgraph_namespace_recommendation_total_memory_requests_savings) by (cluster)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Memory Limit Rightsizings",
     "type": "table",
     "description": "Before and After observations of rightsizing values across clusters.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 192 },
     "fieldConfig": { "defaults": { "unit": "decgbytes" } },
     "targets": [
      {
       "expr": "sum(costgraph_namespace_recommendation_total_memory_limits) by (cluster)"
      },
      {
       "expr": "sum(costgraph_namespace_recommendation_total_memory_limits - costgraph_namespace_recommendation_total_memory_limits_savings) by (cluster)"
      }
     ]
    }
   ]
  },
  {
   "title": "Clusters",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 },
   "collapsed": true,
   "panels": [
    {
     "title": "Current Spend",
     "type": "stat",
     "description": "Aggregate current spend for the organization.",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 11 },
     "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(costgraph_namespace_recommendation_current_spend) by (cluster)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Savings",
     "type": "stat",
     "description": "Aggregate savings for the organization.",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 11 },
     "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(costgraph_namespace_recommendation_total_resource_savings_amount) by (cluster)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "New Spend",
     "type": "stat",
     "description": "Aggregate new spend for the organization.",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 11 },
     "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(costgraph_namespace_recommendation_new_spend) by (cluster)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "CPU Usage",
     "type": "stat",
     "description": "Describes the current CPU usage per cluster",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 171 },
     "fieldConfig": { "defaults": { "unit": "cores" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(costgraph_namespace_recommendation_total_cpu_requests) by (cluster)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "CPU Capacity",
     "type": "stat",
     "description": "Describes the capacity per cluster across nodes backing the workloads.",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 171 },
     "fieldConfig": { "defaults": { "unit": "cores" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(costgraph_cluster_capacity_total_cpu) by (cluster)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "CPU Usage Percent",
     "type": "stat",
     "description": "Describes the current CPU usage percentage per cluster",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 171 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "(sum(costgraph_namespace_recommendation_total_cpu_requests) by (cluster)) / (sum(costgraph_cluster_capacity_total_cpu) by (cluster))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Memory Usage",
     "type": "stat",
     "description": "Describes the current memory usage per cluster",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 179 },
     "fieldConfig": { "defaults": { "unit": "decgbytes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(costgraph_namespace_recommendation_total_memory_requests) by (cluster)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Memory Capacity",
     "type": "stat",
     "description": "Describes the capacity per cluster across nodes backing the workloads.",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 179 },
     "fieldConfig": { "defaults": { "unit": "decgbytes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(costgraph_cluster_capacity_total_memory) by (cluster)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Memory Usage Percent",
     "type": "stat",
     "description": "Describes the current request usage per cluster",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 179 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "(sum(costgraph_namespace_recommendation_total_memory_requests) by (cluster)) / (sum(costgraph_cluster_capacity_total_memory) by (cluster))",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "Nodes",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 },
   "collapsed": true,
   "panels": [
    {
     "title": "Aggregate Node Pricing",
     "type": "stat",
     "description": "Details the monthly cost of all nodes in your organisation",
     "gridPos": { "h": 15, "w": 12, "x": 0, "y": 12 },
     "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "((sum(costgraph_cluster_capacity_nodes_pricing_vcpu_cost) by (cluster) + sum(costgraph_cluster_capacity_nodes_pricing_ram_cost) by (cluster))) * 24 * 30",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Node Pricing",
     "type": "marcusolsson-treemap-panel",
     "description": "Details the monthly cost of nodes per cluster",
     "gridPos": { "h": 15, "w": 12, "x": 12, "y": 12 },
     "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
     "targets": [
      {
       "expr": "((sum(costgraph_cluster_capacity_nodes_pricing_vcpu_cost) by (node, cluster)) + (sum(costgraph_cluster_capacity_nodes_pricing_ram_cost) by (node, cluster))) * 24 * 30",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "Namespace",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 },
   "collapsed": true,
   "panels": [
    {
     "title": "Namespace Cost",
     "type": "timeseries",
     "description": "Cost of workloads running in the namespace.",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 13 },
     "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
     "targets": [
      {
       "expr": "(sum(costgraph_namespace_recommendation_container_recommendations_cpu_current_total_cost_in_dollars) by (namespace)) + (sum(costgraph_namespace_recommendation_container_recommendations_memory_current_total_cost_in_dollars) by (namespace))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Namespace CPU Request",
     "type": "timeseries",
     "description": "CPU requests for the namespaces running across clusters.",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 13 },
     "fieldConfig": { "defaults": { "unit": "cores" } },
     "targets": [
      {
       "expr": "(sum(costgraph_namespace_recommendation_container_recommendations_cpu_current_total_request) by (namespace))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Namespace Memory Request",
     "type": "timeseries",
     "description": "Memory requests for the namespaces running across clusters.",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 13 },
     "fieldConfig": { "defaults": { "unit": "decgbytes" } },
     "targets": [
      {
       "expr": "(sum(costgraph_namespace_recommendation_container_recommendations_memory_current_total_request) by (namespace))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Namespace Cost Savings",
     "type": "timeseries",
     "description": "Cost savings of workloads running in the namespace.",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 173 },
     "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
     "targets": [
      {
       "expr": "(sum(costgraph_namespace_recommendation_container_recommendations_savings_in_dollars) by (namespace))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Namespace CPU Request Savings",
     "type": "timeseries",
     "description": "CPU request savings for the namespaces running across clusters.",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 173 },
     "fieldConfig": { "defaults": { "unit": "cores" } },
     "targets": [
      {
       "expr": "(sum(costgraph_namespace_recommendation_container_recommendations_cpu_savings_request) by (namespace))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Namespace Memory Request Savings",
     "type": "timeseries",
     "description": "Memory request savings for the namespaces running across clusters.",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 173 },
     "fieldConfig": { "defaults": { "unit": "decgbytes" } },
     "targets": [
      {
       "expr": "(sum(costgraph_namespace_recommendation_container_recommendations_memory_savings_request) by (namespace))",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "Workloads",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 },
   "collapsed": true,
   "panels": [
    {
     "title": "Workload Cost",
     "type": "timeseries",
     "description": "Cost of running a container across the namespaces and clusters it runs on.",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 14 },
     "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
     "targets": [
      {
       "expr": "(sum(costgraph_namespace_recommendation_container_recommendations_cpu_current_total_cost_in_dollars) by (container)) + (sum(costgraph_namespace_recommendation_container_recommendations_memory_current_total_cost_in_dollars) by (container))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Workload CPU Request",
     "type": "timeseries",
     "description": "CPU request of a container across the namespaces and clusters it runs on.",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 14 },
     "fieldConfig": { "defaults": { "unit": "cores" } },
     "targets": [
      {
       "expr": "(sum(costgraph_namespace_recommendation_container_recommendations_cpu_current_total_request) by (container))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Workload Memory Request",
     "type": "timeseries",
     "description": "Memory request of a container across the namespaces and clusters it runs on.",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 14 },
     "fieldConfig": { "defaults": { "unit": "decgbytes" } },
     "targets": [
      {
       "expr": "(sum(costgraph_namespace_recommendation_container_recommendations_memory_current_total_request) by (container))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Workload Cost Savings",
     "type": "timeseries",
     "description": "Cost  saving of running a container across the namespaces and clusters it runs on.",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 38 },
     "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
     "targets": [
      {
       "expr": "(sum(costgraph_namespace_recommendation_container_recommendations_savings_in_dollars) by (container)) ",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Workload CPU Request Savings",
     "type": "timeseries",
     "description": "CPU request savings of a container across the namespaces and clusters it runs on.",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 38 },
     "fieldConfig": { "defaults": { "unit": "cores" } },
     "targets": [
      {
       "expr": "(sum(costgraph_namespace_recommendation_container_recommendations_cpu_savings_total_request) by (container))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Workload Memory Request Savings",
     "type": "timeseries",
     "description": "Memory request savings of a container across the namespaces and clusters it runs on.",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 38 },
     "fieldConfig": { "defaults": { "unit": "decgbytes" } },
     "targets": [
      {
       "expr": "(sum(costgraph_namespace_recommendation_container_recommendations_memory_savings_total_request) by (container))",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "Rightsizing",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 },
   "collapsed": true,
   "panels": [
    {
     "title": "Minimum CPU Rightsizings",
     "type": "table",
     "description": "Minimum CPU rightsizing recommendations across clusters per workload.",
     "gridPos": { "h": 11, "w": 12, "x": 0, "y": 107 },
     "fieldConfig": { "defaults": { "unit": "cores" } },
     "targets": [
      {
       "expr": "min(costgraph_namespace_recommendation_container_recommendations_cpu_current_request) by (container)"
      },
      {
       "expr": "min(costgraph_namespace_recommendation_container_recommendations_cpu_current_limit) by (container)"
      },
      {
       "expr": "min(costgraph_namespace_recommendation_container_recommendations_cpu_recommended_request) by (container)"
      },
      {
       "expr": "min(costgraph_namespace_recommendation_container_recommendations_cpu_recommended_limit) by (container)"
      },
      {
       "expr": "((min(costgraph_namespace_recommendation_container_recommendations_cpu_current_total_request) by (container)) - (min(costgraph_namespace_recommendation_container_recommendations_cpu_recommended_total_request) by (container)))"
      },
      {
       "expr": "((min(costgraph_namespace_recommendation_container_recommendations_cpu_current_total_limit) by (container)) - (min(costgraph_namespace_recommendation_container_recommendations_cpu_recommended_total_limit) by (container)))"
      }
     ]
    },
    {
     "title": "Maximum CPU Rightsizings",
     "type": "table",
     "description": "Maximum CPU rightsizing recommendations across clusters per workload.",
     "gridPos": { "h": 11, "w": 12, "x": 12, "y": 107 },
     "fieldConfig": { "defaults": { "unit": "cores" } },
     "targets": [
      {
       "expr": "max(costgraph_namespace_recommendation_container_recommendations_cpu_current_request) by (container)"
      },
      {
       "expr": "max(costgraph_namespace_recommendation_container_recommendations_cpu_current_limit) by (container)"
      },
      {
       "expr": "max(costgraph_namespace_recommendation_container_recommendations_cpu_recommended_request) by (container)"
      },
      {
       "expr": "max(costgraph_namespace_recommendation_container_recommendations_cpu_recommended_limit) by (container)"
      },
      {
       "expr": "((max(costgraph_namespace_recommendation_container_recommendations_cpu_current_total_request) by (container)) - (max(costgraph_namespace_recommendation_container_recommendations_cpu_recommended_total_request) by (container)))"
      },
      {
       "expr": "((max(costgraph_namespace_recommendation_container_recommendations_cpu_current_total_limit) by (container)) - (max(costgraph_namespace_recommendation_container_recommendations_cpu_recommended_total_limit) by (container)))"
      }
     ]
    },
    {
     "title": "Minimum Memory Rightsizings",
     "type": "table",
     "description": "Minimum Memory rightsizing recommendations across clusters per workload.",
     "gridPos": { "h": 11, "w": 12, "x": 0, "y": 156 },
     "fieldConfig": { "defaults": { "unit": "decgbytes" } },
     "targets": [
      {
       "expr": "min(costgraph_namespace_recommendation_container_recommendations_memory_current_request) by (container)"
      },
      {
       "expr": "min(costgraph_namespace_recommendation_container_recommendations_memory_current_limit) by (container)"
      },
      {
       "expr": "min(costgraph_namespace_recommendation_container_recommendations_memory_recommended_request) by (container)"
      },
      {
       "expr": "min(costgraph_namespace_recommendation_container_recommendations_memory_recommended_limit) by (container)"
      },
      {
       "expr": "((min(costgraph_namespace_recommendation_container_recommendations_memory_current_total_request) by (container)) - (min(costgraph_namespace_recommendation_container_recommendations_memory_recommended_total_request) by (container)))"
      },
      {
       "expr": "((min(costgraph_namespace_recommendation_container_recommendations_memory_current_total_limit) by (container)) - (min(costgraph_namespace_recommendation_container_recommendations_memory_recommended_total_limit) by (container)))"
      }
     ]
    },
    {
     "title": "Maximum Memory Rightsizings",
     "type": "table",
     "description": "Maximum memory rightsizing recommendations across clusters per workload.",
     "gridPos": { "h": 11, "w": 12, "x": 12, "y": 156 },
     "fieldConfig": { "defaults": { "unit": "decgbytes" } },
     "targets": [
      {
       "expr": "max(costgraph_namespace_recommendation_container_recommendations_memory_current_request) by (container)"
      },
      {
       "expr": "max(costgraph_namespace_recommendation_container_recommendations_memory_current_limit) by (container)"
      },
      {
       "expr": "max(costgraph_namespace_recommendation_container_recommendations_memory_recommended_request) by (container)"
      },
      {
       "expr": "max(costgraph_namespace_recommendation_container_recommendations_memory_recommended_limit) by (container)"
      },
      {
       "expr": "((max(costgraph_namespace_recommendation_container_recommendations_memory_current_total_request) by (container)) - (max(costgraph_namespace_recommendation_container_recommendations_memory_recommended_total_request) by (container)))"
      },
      {
       "expr": "((max(costgraph_namespace_recommendation_container_recommendations_memory_current_total_limit) by (container)) - (max(costgraph_namespace_recommendation_container_recommendations_memory_recommended_total_limit) by (container)))"
      }
     ]
    }
   ]
  },
  { "title": "Resource Quotas", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 } },
  {
   "title": "Current CPU Quota ",
   "type": "barchart",
   "description": "Maximum resource quota value for the namespace across all clusters.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "cores" } },
   "targets": [
    {
     "expr": "max(costgraph_namespace_recommendation_resource_quota_recommendations_cpu_current) by (namespace)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Recommended CPU Quota ",
   "type": "barchart",
   "description": "Maximum resource quota value for the namespace across all clusters.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "cores" } },
   "targets": [
    {
     "expr": "max(costgraph_namespace_recommendation_resource_quota_recommendations_cpu_recommended) by (namespace)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Current Memory Quota ",
   "type": "barchart",
   "description": "Maximum resource quota value for the namespace across all clusters.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "cores" } },
   "targets": [
    {
     "expr": "max(costgraph_namespace_recommendation_resource_quota_recommendations_memory_current) by (namespace)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Recommended Memory Quota ",
   "type": "barchart",
   "description": "Maximum resource quota value for the namespace across all clusters.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "decgbytes" } },
   "targets": [
    {
     "expr": "max(costgraph_namespace_recommendation_resource_quota_recommendations_memory_recommended) by (namespace)",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}